### ISSUE TITLE
Help documentation for 'Target' instead of 'Field to check'

### ISSUE THREAD

**Issue by QAInsights** [Blazemeter/CorrelationRecorder#10]
`Target` help documentation is misplaced under `Field to Check` section in [ReadMe](https://github.com/Blazemeter/CorrelationRecorder#list-of-correlation-extractors).

![image](https://user-images.githubusercontent.com/2826376/83933883-0cd14700-a79c-11ea-8157-8c9cfeebf90f.png)

**Comment by RicardoPoleo** [comment]
We corrected this, among other names, in the documentation. Also added some helpers to help you out during the configuration, in [our last release](https://github.com/Blazemeter/CorrelationRecorder/releases).

Please, check it out.

I'll be closing this issue.
