### ISSUE TITLE
Repositories Manager window always on top

### ISSUE THREAD

**Issue by QAInsights** [Blazemeter/CorrelationRecorder#11]
After launching `Repositories Manager`, it always stays on top which is making the user difficult to focus on other windows/apps.

![image](https://user-images.githubusercontent.com/2826376/83934083-7b62d480-a79d-11ea-8d6e-8b22b85ef036.png)

**Comment by RicardoPoleo** [comment]
This behavior was corrected in our [last release](https://github.com/Blazemeter/CorrelationRecorder/releases) and now it isn't as invasive as you reported.

Hope you enjoy it.

Happy hacking!
