### ISSUE TITLE
LR to JMeter Correlation Rules converter 

### ISSUE THREAD

**Issue by QAInsights** [Blazemeter/CorrelationRecorder#14]
Hi @RicardoPoleo @Baraujo25 
I created this simple utility which converts LR rules to JMeter correlation recorder rules. Please check it out. Thanks!

[https://github.com/QAInsights/LoadRunner-to-JMeter-Correlation-Rules-Converter](https://github.com/QAInsights/LoadRunner-to-JMeter-Correlation-Rules-Converter)

**Comment by rabelenda** [comment]
Nice! Sounds really helpful! You can also check [shiflteft converter](https://shiftleft.blazemeter.com/) which currently does not have support for converting correlations, but allows converting most of LR scripts to JMeter & [Taurus](https://gettaurus.org/).

**Comment by QAInsights** [comment]
Thanks @rabelenda. Yes I am aware of shiftleft converter :)

**Comment by RicardoPoleo** [comment]
Hello, @QAInsights, 

Thanks for adding this awesome functionality. We are flattered. we added a task in the back to review it in-depth or add it to the readme on future releases.

Keep on with the great work and, as always:

Happy Hacking!
