### ISSUE TITLE
 Disabling Correlation Rules not working

### ISSUE THREAD

**Issue by QAInsights** [Blazemeter/CorrelationRecorder#15]
Retested #13 

@RicardoPoleo I tested the patch release 1.1.1, it seems that the issue still persists. Here is the recording [https://share.qainsights.com/llu2K6XR](https://share.qainsights.com/llu2K6XR).

**Comment by RicardoPoleo** [comment]
Hello, @QAInsights

We will consider this for a future release. I'm sorry for the persistence of this issue. We did add it to our backlog and will tackle it as soon as possible. 

In the meantime, we thank you for testing the app and taking the time to report it. 

Happy Hacking and keep up with the awesome work.

**Comment by RicardoPoleo** [comment]
Hello, @QAInsights

We fixed this behaviour on most of the themes for different JMeter versions. Could you give the v1.2 a try on your environment and let us know if it is fixed for you.

Hope to hear from you soon,

**Comment by RicardoPoleo** [comment]
Hello @QAInsights,

Hope you are doing great.

I'll close this issue to the lack of activity. If you feel it is necessary to fix something regarding this particular topic, please, don't hesitate to reopen it.

Happy hacking!
