### ISSUE TITLE
Regarding Blazemeter-Correlation Recorder Plugin

### ISSUE THREAD

**Issue by RagaveniSundaresan** [Blazemeter/CorrelationRecorder#19]
I added bzm-correlation recorder plugin in Jmeter(version 5.1.1). As per the documentaion, I gave correlation rules and captured the scenario.
Result I got:
As expected, regular expression extractor is automatically added to the request which matches the regular expression given in correlation rule.
But the dynamic value in the subsequent request is not replaced by reference variable which has to be replaced automatically.

Kindly guide me to solve this issue. Thanks in advance.

**Comment by Baraujo25** [comment]
Hello @RagaveniSundaresan,

Thanks for reaching out.

We have a few questions in order to better understand your issue:
1. Where do you want to place the extracted value? (Body, URL, etc.)
2. Is your replacement regular expression correct?
 In order to verify if the regular expression is working, you can select on your view result tree the sampler that *should* contain the value replaced on the request. Then you can search on the whole request for the replacement expression.
 
    The following image illustrates how to verify the replacement expression:
 
   ![Screen Shot 2021-02-19 at 10 57 11](https://user-images.githubusercontent.com/48018971/108514008-122adf00-72a2-11eb-89ab-16fe5200b8e0.png)

3. Would you be able to share more information about the extraction and replacement you are trying to do? Like the correlation rule configuration (showing the replacement RegEx), the request where you have to place the extracted value.

I'll be looking forward to your response.

Best,

Joaquin.

**Comment by RagaveniSundaresan** [comment]
> Hello @RagaveniSundaresan,
> 
> Thanks for reaching out.
> 
> We have a few questions in order to better understand your issue:
> 
> 1. Where do you want to place the extracted value? (Body, URL, etc.)
> 2. Is your replacement regular expression correct?
>    In order to verify if the regular expression is working, you can select on your view result tree the sampler that _should_ contain the value replaced on the request. Then you can search on the whole request for the replacement expression.
>    The following image illustrates how to verify the replacement expression:
>    ![Screen Shot 2021-02-19 at 10 57 11](https://user-images.githubusercontent.com/48018971/108514008-122adf00-72a2-11eb-89ab-16fe5200b8e0.png)
> 3. Would you be able to share more information about the extraction and replacement you are trying to do? Like the correlation rule configuration (showing the replacement RegEx), the request where you have to place the extracted value.
> 
> I'll be looking forward to your response.
> 
> Best,
> 
> Joaquin.

Hi @Baraujo25 

Thanks for responding.
I want to place the extracted value in request body and I am pretty sure that my regular expression is right.
For your reference I will attach my script here. 
[Shopitv60 Correlation recorder test.zip](https://github.com/Blazemeter/CorrelationRecorder/files/6068578/Shopitv60.Correlation.recorder.test.zip)

![image](https://user-images.githubusercontent.com/79318071/109649172-89555280-7b81-11eb-8433-9d434fe6c5b1.png)
Regular expression extractor is automatically added to the HTTP request no.213
This extracted value has to be placed under HTTP request no 223, but not replacing. This is where I am facing issue.

Kindly guide me through this. Thanks in advance!
Let me know for any further details if needed.

Regards,
Ragaveni

**Comment by RicardoPoleo** [comment]
Hello @RagaveniSundaresan ,

After checking the TestPlan you sent, realized that you were using the same regex for the Replacement as you did for the Extractor. This could work on many occasions and, in this particular case, it doesn't. 

Remember that, once the Correlation Extractor is applied in the _Response_, the value will be stored in the reference variable. From that point onward, the regex used for the Correlation Replacement needs to be matched against the _Requests_.

For I could see in the TestPlan, and corroborate later when doing a recording on http://demo.borland.com/ShopItV60 myself, the value you wanted to replace was the argument called sid (you mentioned it before as well ;) ), which always follows this structure: 

```
sid=12345676
```

a.k.a.: sid=a bunch of numbers

There are multiple ways to catch this value, I used `sid=([0-9]*)` and it worked like a charm. The following search on the View Result Tree of my test display that it does, indeed, match the argument in the request.

![ReplacementSearch](https://user-images.githubusercontent.com/7467545/109676741-c3116380-7b57-11eb-9c38-d55805af1c20.png)


Remember to always try to use the regex that: 
1. Matches the value you are searching to replace
2. Reduce the scope of the matched elements 

With point 2 in mind, you could go one step farther and use `sid=([0-9]{9})` as the Replacement's Regex, if you know for certain that the sid will not grow bigger than 9 numbers.

Either way, the final rule will look like this:

![Screen Shot 2021-03-02 at 13 01 49](https://user-images.githubusercontent.com/7467545/109677586-93af2680-7b58-11eb-81e7-f10158a9c22b.png)

Please, let me know if this solves your issue or if you need any further support.

Than been said, hope you have a great day and, as always:

Happy Hacking!

**Comment by RicardoPoleo** [comment]
Well, @RagaveniSundaresan

Since we haven't heard from you in a while, I'll close this issue. 

If you have any doubt, please don't hesitate to open this issue once again.

See you around!
