### ISSUE TITLE
Requests are delayed while recording

### ISSUE THREAD

**Issue by RagaveniSundaresan** [Blazemeter/CorrelationRecorder#22]
While recording the scenario with bzm correlation recorder plugin, requests are not captured in expected order. 
For example,
Expected order is:
request1
request2
request3(values passed in this request depends on the response of request1)

Order obtained is:
request3(values passed in this request depends on the response of request1)
request2
request1

Since request1 is captured only after request3, autocorrelation is not working at this point. 
But when used with HTTPS Test script recorder, request are captured in expected order.

It would be time saving if this issue is resolved. Kindly do the needful.

**Comment by RicardoPoleo** [comment]
Hello @RagaveniSundaresan,

Thanks for taking the time to report this behaviour. We highly appreciate it.

On a regular basis, please, let us know the version that you are using, so we can replicate the issue (JMeter's, Correlation Recorder's, and so on). However, for this particular behaviour, we will be releasing a fix on v1.2. 

Please stay tuned for our [last releases ](https://github.com/Blazemeter/CorrelationRecorder/releases) and, as always,

Happy hacking!

**Comment by RagaveniSundaresan** [comment]
Hi @RicardoPoleo 

Thanks for considering this issue!

My Jmeter version is 5.1.1 and bzm correlation recorder plugin version is 1.1.2

**Comment by RicardoPoleo** [comment]
Hello @RagaveniSundaresan,

The new version of the plugin is now available in the Plugin Manager. Wanna try it out and see if your issue is fixed with the new implementation?

Hope to hear from you soon,

**Comment by RicardoPoleo** [comment]
Hello @RagaveniSundaresan,

Hope you are doing amazing. I'll be closing this issue, due to inactivity, however, if you feel the need to let us know any problem regarding this, please don't hesitate to reopen it.

Happy Hacking!
