### ISSUE TITLE
Target dropdown width increase

### ISSUE THREAD

**Issue by QAInsights** [Blazemeter/CorrelationRecorder#3]
Could you please increase the width of `Target` drop down to see the text clearly? Please refer below screenshot.

![image](https://user-images.githubusercontent.com/2826376/83708825-b1bd1a00-a60c-11ea-9efe-602e206093a2.png)

**Comment by Baraujo25** [comment]
Hello,

Thank you again for reporting issues that help us improve the plugin. 

We have added your concern to our backlog. You will be able to visualize the results on the next release. 

Best regards,

**Comment by RicardoPoleo** [comment]
Hello, @QAInsights  

This issue, among others you reported, was corrected in our [last release](https://github.com/Blazemeter/CorrelationRecorder/releases). Please check it out.

I'm going to close this issue and, if you have any trouble, don't hesitate to open it again.

Have an amazing day,
