### ISSUE TITLE
Tool Tip for fields issue

### ISSUE THREAD

**Issue by Adhithyaram** [Blazemeter/CorrelationRecorder#4]
Tool Tip for Match Number and Group Number fields in the Correlation Rules tab is interchanged.
![GroupNumber](https://user-images.githubusercontent.com/66354160/83767829-b7157580-a69b-11ea-8cdd-cd9db25491a9.jpg)
![MatchNumber](https://user-images.githubusercontent.com/66354160/83767840-b8df3900-a69b-11ea-8bb7-d599dc9fee37.jpg)

**Comment by RicardoPoleo** [comment]
Hello, @QAInsights  

This issue, among others you reported, was corrected in our [last release](https://github.com/Blazemeter/CorrelationRecorder/releases), also, the UI was changed (for an easier configuration and understanding of a rule). Please check it out.

I'm going to close this issue and, if you have any trouble, don't hesitate to open it again.

and, as always, have a great day,
