### ISSUE TITLE
Checkbox/Toggle to enable/disable rules

### ISSUE THREAD

**Issue by QAInsights** [Blazemeter/CorrelationRecorder#6]
Can we get a checkbox or toggle on/off rules in the Correlation Rules tab? This will allow users to easily enable/disable rules instead of deleting them. Thanks!

![image](https://user-images.githubusercontent.com/2826376/83780059-32ffc580-a67c-11ea-8901-e948c4bb88c9.png)

**Comment by RicardoPoleo** [comment]
This, among other visual changes, was introduced on our [last release](https://github.com/Blazemeter/CorrelationRecorder/releases). Now disabling a rule will prevent it to be applied during the recording.

We really appreciated your input and we would like to hear more. 

I'll be closing this issue but, don't hesitate to open it again if you have any issues with it.

Happy testing and enjoy.
