### ISSUE TITLE
Correlation Replacement not working

### ISSUE THREAD

**Issue by QAInsights** [Blazemeter/CorrelationRecorder#7]
When I try to replace the correlated values by configuring Correlation Replacement regex, it is not getting replaced successfully. 

JMX file https://send.firefox.com/download/74e790bc0fee9ee5/#0CMN95l1ZL1rwhAaW6whZA

URL: https://petstore.octoperf.com/

![image](https://user-images.githubusercontent.com/2826376/83931715-b8bf6600-a78d-11ea-85e3-3fea62ac163a.png)

Debug Sampler

![image](https://user-images.githubusercontent.com/2826376/83931765-f45a3000-a78d-11ea-8880-e910fd95bea3.png)

Rules
![image](https://user-images.githubusercontent.com/2826376/83931783-05a33c80-a78e-11ea-95c1-c4433e751e54.png)

**Comment by ThiruOnNet** [comment]
Is correlation replacement for variable cat set to viewCategory\=\??

Is it expected?

-ThiruOnNet

**Comment by QAInsights** [comment]
Yes @ThiruOnNet I am extracting it in the prior request and it suppose to replace the value. As far as I observed, the replacement works only in the Header Managers, not on HTTP requests. All the details you can see it in the screenshots.

**Comment by rabelenda** [comment]
Hello @QAInsights, 

I think that what @ThiruOnNet wanted to note is that you are using in replacement regex a value that starts like "viewCategory\=\" and you are expecting a non matching parameter named categoryId to be replaced in the request (per the screenshot you shared). If that is the case, you need to change replacement regex.

Regards

**Comment by QAInsights** [comment]
Thanks @rabelenda for pointing out. I was trying multiple regex and parameters. I would have attached the wrong screenshot. My bad. I have tested the replacement functionality in 1.1 version. I tried various regex to replace the correlated value. It is not working. I am not sure whether I am making any mistakes from my end :(. But the session ID is getting replaced, not the category ID.  I tried @ThiruOnNet regex as well, it is not replacing. Test plan has been attached.

**Comment by QAInsights** [comment]
@Baraujo25 @rpoleo 
[bzm - Correlation Recorder.zip](https://github.com/Blazemeter/CorrelationRecorder/files/5424113/bzm.-.Correlation.Recorder.zip)

**Comment by RicardoPoleo** [comment]
Hello, @QAInsights 

This looks, weird. I'm adding this again to the backlog and tackle it. If the issue is on our end, rest assured, we will solve it. Otherwise, we will let you know what was the issue, and help you fix it.

Again, thanks for taking the time.

**Comment by RicardoPoleo** [comment]
Hello @QAInsights 

After checking the Test Plan & the images you sent us, I can see that the Regex used for the replacements seems to be off.

For example, the rule with the reference variable "cat", even though the Correlation Extractor is extracting a value (eg: FISH) using the regex `categoryId=(.+?)"` (with MatchNr=1 and GroupNr=1) from the body, when it comes to the Correlation Replacement, the regex `categoryId=??` wont match the value in the URL.  

On the petstore.octoperf.com page, the URL with the category looks like this:
`https://petstore.octoperf.com/actions/Catalog.action?viewCategory=&categoryId=FISH`
Using that regex, you only match `categoryId` (and the fish value isn't captured), therefore, when comparing with the stored value, no matching is made, and it doesn't apply the replacement.

I tested using something like `categoryId=(.+)` instead, matching `categoryId=FISH` and obtaining `FISH` from it, which is stored in the `cat` variable by the time the request is made.

I encourage you to test it out (and review the rest of the replacements regex based on that) and see how it goes.

**Comment by RicardoPoleo** [comment]
Aside from this, if you need more detailed help on how to capture the values in a flow, or some guide for those amazing replacements you got there, I encourage you to share the JTLs of the recording (with the info of the requests and the responses from the server, as XML pref), so we can give an accurate response for it.

Hope this helps you and, as always,

Happy Hacking!

**Comment by QAInsights** [comment]
@RicardoPoleo I did a fresh installation of JMeter and the plugin, the replacement is working fine. Thanks for the inputs. Let me work on the jtl file. I'm closing this issue. Thanks.
